{
 "title": "Flink Metrics - simple version",
 "description": "Flink Metrics for skewed data and CPU intensive processing",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "2m",
 "templating": {
  "list": [
   {
    "name": "Topics",
    "query": "label_values(kafka_log_logstartoffset, topic)"
   },
   {
    "name": "Broker",
    "label": "Kafka Broker",
    "query": "label_values(kafka_log_size, instance)"
   },
   {
    "name": "Zookeeper",
    "label": "Kafka Zookeeper",
    "query": "label_values(zookeeper_InitLimit,instance)"
   },
   {
    "name": "Flink_Job_Name",
    "query": "label_values(flink_jobmanager_job_uptime,job_name)"
   },
   {
    "name": "Source",
    "query": "label_values(flink_taskmanager_job_task_numRecordsInPerSecond,task_name)"
   },
   {
    "name": "Sink",
    "query": "label_values(flink_taskmanager_job_task_numRecordsInPerSecond,task_name)"
   },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Pods",
    "query": "label_values(kube_pod_container_info,pod)"
   }
  ]
 },
 "panels": [
  { "title": "Jobs overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Task slots",
   "type": "singlestat",
   "description": "Total number of task slots on the Flink cluster",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal",
     "legendFormat": "Total task slots"
    }
   ]
  },
  {
   "title": "Available task slots",
   "type": "singlestat",
   "description": "Available tasks slots on the Flink cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable"
    }
   ]
  },
  {
   "title": "# CPU cores",
   "type": "bargauge",
   "description": "The number of CPU cores on each node of the cluster. This panel will be updated only if you start node_exporter \"sudo systemctl [status|start|stop] node_exporter\".",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Job's elapsed time running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "flink_jobmanager_job_uptime", "legendFormat": "{{job_name}}" }
   ]
  },
  {
   "title": "Task Managers",
   "type": "singlestat",
   "description": "The total number of Task Managers (TM) on the Flink cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "singlestat",
   "description": "The total number of running jobs on the Flink cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs",
     "legendFormat": "Running Jobs"
    }
   ]
  },
  {
   "title": "CPU metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Manager CPU usage per core",
     "type": "graph",
     "description": "This panel has queries for each CPU core. Hence, if the cluster has more cores available it will be necessary to add queries manually.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_System_CPU_Usage",
       "legendFormat": "{{host}} - Usage"
      },
      {
       "expr": "flink_jobmanager_System_CPU_UsageCPU0",
       "legendFormat": "{{host}} - Usage CPU 0"
      },
      {
       "expr": "flink_jobmanager_System_CPU_UsageCPU1",
       "legendFormat": "{{host}} - Usage CPU 1"
      },
      {
       "expr": "flink_jobmanager_System_CPU_UsageCPU2",
       "legendFormat": "{{host}} - Usage CPU 2"
      },
      {
       "expr": "flink_jobmanager_System_CPU_UsageCPU3",
       "legendFormat": "{{host}} - Usage CPU 3"
      },
      {
       "expr": "flink_jobmanager_System_CPU_UsageCPU4",
       "legendFormat": "{{host}} - Usage CPU 4"
      },
      {
       "expr": "flink_jobmanager_System_CPU_UsageCPU5",
       "legendFormat": "{{host}} - Usage CPU 5"
      },
      {
       "expr": "flink_jobmanager_System_CPU_UsageCPU6",
       "legendFormat": "{{host}} - Usage CPU 6"
      },
      {
       "expr": "flink_jobmanager_System_CPU_UsageCPU7",
       "legendFormat": "{{host}} - Usage CPU 7"
      }
     ]
    },
    {
     "title": "Task Manager CPU usage per core",
     "type": "graph",
     "description": "This panel has queries for each CPU core. Hence, if the cluster has more cores available it will be necessary to add queries manually.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_System_CPU_Usage",
       "legendFormat": "{{host}} - Usage"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU0",
       "legendFormat": "{{host}} - Usage CPU 0"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU1",
       "legendFormat": "{{host}} - Usage CPU 1"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU2",
       "legendFormat": "{{host}} - Usage CPU 2"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU3",
       "legendFormat": "{{host}} - Usage CPU 3"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU4",
       "legendFormat": "{{host}} - Usage CPU 4"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU5",
       "legendFormat": "{{host}} - Usage CPU 5"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU6",
       "legendFormat": "{{host}} - Usage CPU 6"
      },
      {
       "expr": "flink_taskmanager_System_CPU_UsageCPU7",
       "legendFormat": "{{host}} - Usage CPU 7"
      }
     ]
    },
    {
     "title": "Job Manager CPU load 1, 5, 15 minutes per node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_System_CPU_Load1min",
       "legendFormat": "{{host}} - load 1 minute"
      },
      {
       "expr": "flink_jobmanager_System_CPU_Load5min",
       "legendFormat": "{{host}} - load 5 minute"
      },
      {
       "expr": "flink_jobmanager_System_CPU_Load15min",
       "legendFormat": "{{host}} - load 15 minute"
      }
     ]
    },
    {
     "title": "Task Manager CPU load 1, 5, 15 minutes per node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_System_CPU_Load1min",
       "legendFormat": "{{host}} - load 1 minute"
      },
      {
       "expr": "flink_taskmanager_System_CPU_Load5min",
       "legendFormat": "{{host}} - load 5 minute"
      },
      {
       "expr": "flink_taskmanager_System_CPU_Load15min",
       "legendFormat": "{{host}} - load 15 minute"
      }
     ]
    },
    {
     "title": "Job Manager CPU Idle, Usage, User per node",
     "type": "graph",
     "description": "This panel shows what the \"top\" linux command line exports to Prometheus and Grafana.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_System_CPU_Idle",
       "legendFormat": "{{host}} - CPU Idle"
      },
      {
       "expr": "flink_jobmanager_System_CPU_Usage",
       "legendFormat": "{{host}} - CPU Usage"
      },
      {
       "expr": "flink_jobmanager_System_CPU_User",
       "legendFormat": "{{host}} - CPU User"
      }
     ]
    },
    {
     "title": "Task Manager CPU Idle, Usage, User per node",
     "type": "graph",
     "description": "This panel shows what the \"top\" linux command line exports to Prometheus and Grafana.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_System_CPU_Idle",
       "legendFormat": "{{host}} - CPU Idle"
      },
      {
       "expr": "flink_taskmanager_System_CPU_Usage",
       "legendFormat": "{{host}} - CPU Usage"
      },
      {
       "expr": "flink_taskmanager_System_CPU_User",
       "legendFormat": "{{host}} - CPU User"
      }
     ]
    },
    {
     "title": "Job Manager CPU IO Wait, IRQ, Soft IRQ, Sys",
     "type": "graph",
     "description": "An interrupt request (or IRQ) is a hardware signal sent to the processor that temporarily stops a running program and allows a special program, an interrupt handler, to run instead.\nIOWait - % of IOWait CPU usage on the machine.\nSys - % of System CPU usage on the machine.\nIrq - % of Irq CPU usage on the machine.\nSoft Irq - % of SoftIrq CPU usage on the machine.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_System_CPU_IOWait",
       "legendFormat": "{{host}} - CPU IO Wait"
      },
      {
       "expr": "flink_jobmanager_System_CPU_Irq",
       "legendFormat": "{{host}} - CPU Irq (interrupt request)"
      },
      {
       "expr": "flink_jobmanager_System_CPU_SoftIrq",
       "legendFormat": "{{host}} - CPU Soft Irq (soft interrupt request)"
      },
      {
       "expr": "flink_jobmanager_System_CPU_Sys",
       "legendFormat": "{{host}} - CPU Sys"
      }
     ]
    },
    {
     "title": "Task Manager CPU IO Wait, IRQ, Soft IRQ, Sys",
     "type": "graph",
     "description": "An interrupt request (or IRQ) is a hardware signal sent to the processor that temporarily stops a running program and allows a special program, an interrupt handler, to run instead.\nIOWait - % of IOWait CPU usage on the machine.\nSys - % of System CPU usage on the machine.\nIrq - % of Irq CPU usage on the machine.\nSoft Irq - % of SoftIrq CPU usage on the machine.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_System_CPU_IOWait",
       "legendFormat": "{{host}} - CPU IO Wait"
      },
      {
       "expr": "flink_taskmanager_System_CPU_Irq",
       "legendFormat": "{{host}} - CPU Irq (interrupt request)"
      },
      {
       "expr": "flink_taskmanager_System_CPU_SoftIrq",
       "legendFormat": "{{host}} - CPU Soft Irq (soft interrupt request)"
      },
      {
       "expr": "flink_taskmanager_System_CPU_Sys",
       "legendFormat": "{{host}} - CPU Sys"
      }
     ]
    },
    {
     "title": "Thread counter on Task Manager's",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "Number of threads" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Threads_Count",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "CPU LOAD - Job/Task Managers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "percentunit", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_CPU_Load",
       "legendFormat": "JobManager ({{host}})"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_CPU_Load",
       "legendFormat": "TaskManager ({{host}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Manager memory",
     "type": "graph",
     "description": "Memory total and available at the Job Manager",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decgbytes", "label": "Giga bytes" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_System_Memory_Total",
       "legendFormat": "{{host}} - Total"
      },
      {
       "expr": "flink_jobmanager_System_Memory_Available",
       "legendFormat": "{{host}} - Available"
      }
     ]
    },
    {
     "title": "Task Manager memory",
     "type": "graph",
     "description": "Memory total and available at the Task Managers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "decgbytes", "label": "Giga bytes" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_System_Memory_Total",
       "legendFormat": "{{host}} - Total"
      },
      {
       "expr": "flink_taskmanager_System_Memory_Available",
       "legendFormat": "{{host}} - Available"
      }
     ]
    },
    {
     "title": "JobManager and TaskManager Buffers",
     "type": "graph",
     "description": "JVM Memory Direct Buffers vs JVM Memory Total Capacity of Direct Buffers",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decbytes", "label": "MBytes" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed",
       "legendFormat": "Job Manager ({{host}}) memory used"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Direct_TotalCapacity",
       "legendFormat": "Job Manager ({{host}}) memory available"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed",
       "legendFormat": "Task Manager ({{host}}) memory used"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity",
       "legendFormat": "Task Manager ({{host}}) memory available"
      }
     ]
    },
    {
     "title": "JobManager and TaskManager Heap Memory",
     "type": "graph",
     "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
       "legendFormat": "JobManager ({{host}}) Used"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max",
       "legendFormat": "JobManager ({{host}}) Available"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
       "legendFormat": "TaskManager ({{host}}) Used"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max",
       "legendFormat": "TaskManager ({{host}}) Available"
      }
     ]
    }
   ]
  },
  {
   "title": "Job metrics (throughput of each operator)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "records/sec IN of each operator by Task Manager",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Number of Records/sec" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_numRecordsInPerSecond",
       "legendFormat": "{{host}}-{{task_name}}"
      }
     ]
    },
    {
     "title": "records/sec OUT of each operator by Task Manager",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Number of Records/sec" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond",
       "legendFormat": "{{host}}-{{task_name}}"
      }
     ]
    },
    {
     "title": "records/sec IN and OUT of each operator by Task Manager",
     "type": "graph",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Number of Records/sec - INPUT" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_numRecordsInPerSecond{operator_name=\"pre_aggregate\"}",
       "legendFormat": "{{host}}-{{task_name}}-IN"
      },
      {
       "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond{operator_name=\"pre_aggregate\"}",
       "legendFormat": "{{host}}-{{task_name}}-OUT"
      }
     ]
    }
   ]
  },
  {
   "title": "Job metrics (latency percentile of each operator)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Pre-aggregation throughput IN/OUT (records/sec) vs. processing latency",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    {
     "format": "short",
     "label": "Input and output throughput (rec/sec)"
    }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsInPerSecond{operator_name=\"pre_aggregate\"}",
     "legendFormat": "{{operator_name}}[{{subtask_index}}]-IN"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond{operator_name=\"pre_aggregate\"}",
     "legendFormat": "{{operator_name}}[{{subtask_index}}]-OUT"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_pre_aggregate_latency_histogram{quantile=\"0.5\"}",
     "legendFormat": "{{operator_name}}[{{subtask_index}}]-50"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_pre_aggregate_latency_histogram{quantile=\"0.99\"}",
     "legendFormat": "{{operator_name}}[{{subtask_index}}]-99"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond{operator_name=\"Source:_source\"}",
     "legendFormat": "{{operator_name}}[{{subtask_index}}]-IN"
    }
   ]
  },
  {
   "title": "Latency tracking from Flink",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{quantile=\"0.99\"}",
     "legendFormat": "{{host}}-{{operator_id}}-quantile[{{quantile}}]"
    }
   ]
  },
  {
   "title": "Pre-aggregation network buffer usage (%) vs. Parameter K",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percent", "label": "Network buffer usage" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_buffers_outPoolUsage{task_name=\"pre_aggregate\"}*100",
     "legendFormat": "{{task_name}}-outPool[{{subtask_index}}]-avg"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_pre_aggregate_outPoolUsage_histogram{quantile=\"0.99\"}",
     "legendFormat": "{{task_name}}-outPool[{{subtask_index}}]-99"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_pre_aggregate_parameter",
     "legendFormat": "{{task_name}}[{{subtask_index}}]-param"
    }
   ]
  },
  {
   "title": "Network and Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "NETWORK - Ratio of the output buffers used per operator",
     "type": "graph",
     "description": "An estimate on the ratio of the output buffers used in the respective local buffer pools.",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "percentunit", "label": "Buffer usage" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_outPoolUsage",
       "legendFormat": "{{host}}-{{task_name}}"
      }
     ]
    },
    {
     "title": "MemorySegments at TaskManager's",
     "type": "graph",
     "description": "MemorySegments at TaskManager's",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_AvailableMemorySegments",
       "legendFormat": "{{host}} - AvailableMemorySegments (shuffle netty)"
      },
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_TotalMemorySegments",
       "legendFormat": "{{host}} - TotalMemorySegments (shuffle netty)"
      }
     ]
    },
    {
     "title": "Number of buffers in local and remote per second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_numBuffersInLocalPerSecond",
       "legendFormat": "{{host}}-{{task_name}} - buffers in local per second"
      },
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_numBuffersInRemotePerSecond",
       "legendFormat": "{{host}}-{{task_name}} - buffers in remote per second"
      }
     ]
    },
    {
     "title": "TaskManagers Garbage Collection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time",
       "legendFormat": "{{host}} Young Gen Time"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time",
       "legendFormat": "{{host}} Old Gen Time"
      }
     ]
    }
   ]
  }
 ]
}